services:
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bytemeifyoucan
      POSTGRES_USER: bytemeifyoucan
      POSTGRES_PASSWORD: propra2
    volumes:
      - pgdata:/var/lib/postgresql/data # Named Volume statt lokaler Ordner

volumes:
  pgdata: # Leere Definition reicht
